### ISSUE TITLE
Improving the state of PouchDB CI

### ISSUE THREAD

**Issue by jcoglan** [pouchdb/pouchdb#8345]
Me and the team at [Neighbourhoodie][NH] (including @AlbaHerrerias, @garbados,
@janl) are trying to ascertain the state of the new `indexeddb` adapter, to get
its functionality and performance to a point where we're confident deploying it
in production and potentially making it a core/default adapter in PouchDB. In
order to do this we've been looking into the current state of the test suite and
CI on Travis. Our first aim is to make sure `indexeddb` has feature parity with
`idb` and passes all the same functional tests, and we're opening this issue to
start a conversation among ourselves and other PouchDB maintainers to get the
build into a state where we're confident this is the case.

We have a [branch][ci-branch] that addresses a few problems we've found with the
build so far:

- Update `pouchdb-express-router` to `0.0.11`, which [fixes the heartbeat
  logic][heartbeat-fix] so that our integration tests work reliably without
  timing out in cases where `changes()` requests need to wait before receiving
  data via long-polling.

- Correct the path used to load PouchDB in
  `express-pouch-minimum-for-pouchdb.js`.

- The `ADAPTER` option appears to do nothing for browser tests; we've unified
  the `ADAPTER` and `ADAPTERS` options and changed `webrunner.js` so that it
  loads any requested adapters if they're packaged as plugins rather than part
  of the core distribution.

- To allow `indexeddb` to be tested, we've turned it into a plugin so that it
  compiles into a file in `packages/node_modules/pouchdb/dist` and can be loaded
  via the `ADAPTERS` option. This might not be desired for including in releases
  but it was the easiest way to get the tests to run with this adapter.

On this branch, I have run the `npm run test` task with various combinations of
options and recorded the results, setting `BAIL=0` so the full suite runs. The
first column in this table indicates whether this combination is currently
configured to run on Travis. Rows marked `y*` are configured, but we believe
that these actually execute the `idb` adapter because of either the `ADAPTER`
variable having no effect, or `indexeddb` not being loaded.

CI  | CLIENT           | ADAPTERS     | PLUGINS      | TYPE        | result
--- | ---------------- | ------------ | ------------ | ----------- | ---------------------------------------
y   | node             |              |              | integration | pass: 1668, pend: 45
y   | node             |              |              | mapreduce   | pass: 415, pend: 2, fail: 16
n   | node             |              | pouchdb-find | find        | pass: 343, pend: 156, fail: 228
n   | node             |              |              | fuzzy       | pass: 1
n   | node             | memory       |              | integration | pass: 1646, pend: 45
n   | node             | memory       |              | mapreduce   | pass: 415, pend: 2, fail: 16
n   | node             | memory       | pouchdb-find | find        | pass: 343, pend: 156, fail: 228
n   | node             | memory       |              | fuzzy       | pass: 1
n   | node             | websql       |              | integration | module not found
y   | selenium:firefox | idb          |              | integration | pass: 1695, pend: 45
n   | selenium:firefox | idb          |              | mapreduce   | pass: 414, pend: 1, fail: 16
n   | selenium:firefox | idb          | pouchdb-find | find        | pass: 343, pend: 156, fail: 228
n   | selenium:firefox | idb          |              | fuzzy       | pass: 1
y*  | selenium:firefox | indexeddb    |              | integration | pass: 1695, pend: 45
y*  | selenium:firefox | indexeddb    |              | mapreduce   | pass: 384, pend: 1, fail: 31 (variable)
n   | selenium:firefox | indexeddb    | pouchdb-find | find        | pass: 68, pend: 137, fail: 230
n   | selenium:firefox | indexeddb    |              | fuzzy       | pass: 1
n   | selenium:firefox | localstorage |              | integration | pass: 400, pend: 10, fail: 40
n   | selenium:firefox | localstorage |              | mapreduce   | pass: 182, fail: 30
n   | selenium:firefox | localstorage | pouchdb-find | find        | pass: 18, pend: 22, fail: 236
n   | selenium:firefox | localstorage |              | fuzzy       | pass: 0, fail: 2
n   | selenium:firefox | memory       |              | integration | pass: 1695, pend: 45
n   | selenium:firefox | memory       |              | mapreduce   | pass: 414, pend: 1, fail: 16
n   | selenium:firefox | memory       | pouchdb-find | find        | pass: 343, pend: 156, fail: 228
n   | selenium:firefox | memory       |              | fuzzy       | pass: 1

We're primarily concerned with making sure `indexeddb` has feature parity with
`idb` but I have included results for other adapters here to provide more
context.

With the `pouchdb-express-router` update applied, the `integration` and `fuzzy`
suites do not show any failures for the adapters we're interested in. The
`localstorage` adapter does show some failures here but that's not our priority.

The default `node` adapter, and the `idb` adapter, show similar results for
`mapreduce` and `find`, with a few failures for `mapreduce` and a large number
of failures and skips for `find`. `indexeddb` gives inconsistent results for
`mapreduce` and a very different result for `find`, which is potentially
concerning as the `find()` method (Mango queries) is the principal
implementation difference between `indexeddb` and `idb`.

Travis also runs the following task, which for me gives the result:

    $ CLIENT=node AUTO_COMPACTION=true npm run test
    -> pass: 1647, pend: 45

Travis does run some tests for `find`. On Node it runs with
`SERVER=couchdb-master` and in the browser it runs `ADAPTER=indexeddb
SERVER=pouchdb-server` (per the above, this is probably running the `idb`
adapter, not `indexeddb`). If neither `COUCH_HOST` nor `SERVER` is set, the
build scripts default to `SERVER=pouchdb-express-router`.

To see if there are environments where the `mapreduce` or `find` tests do not
fail, I have tried running them with various values of the `SERVER` option, and
with `COUCH_HOST` configured to point at my local CouchDB v3.1.1 instance.
(`SERVER=pouchdb-server` also requires setting
`TRAVIS_REPO_SLUG=pouchdb/pouchdb` in order for the build script to set up the
server correctly.)

CI  | CLIENT           | ADAPTERS  | TYPE      | SERVER                  | result
--- | ---------------- | --------- | --------- | ----------------------- | ----------------------------------------
y   | node             |           | mapreduce | pouchdb-express-router  | pass: 415, pend: 2, fail: 16
n   | node             |           | mapreduce | pouchdb-server          | pass: 426, pend: 2, fail: 5 (variable)
n   | node             |           | mapreduce | express-pouchdb-minimum | pass: 419, pend: 2, fail: 12 (v slow)
n   | node             |           | mapreduce | CouchDB v3.1.1          | pass: 333, pend: 2, fail: 98
n   | node             |           | find      | pouchdb-express-router  | pass: 343, pend: 156, fail: 228
n   | node             |           | find      | pouchdb-server          | pass: 642, pend: 268
n   | node             |           | find      | express-pouchdb-minimum | pass: 343, pend: 156, fail: 228
n   | node             |           | find      | CouchDB v3.1.1          | pass: 642, pend: 268
n   | selenium:firefox | idb       | mapreduce | pouchdb-express-router  | pass: 414, pend: 1, fail: 16
n   | selenium:firefox | idb       | mapreduce | pouchdb-server          | pass: 428, pend: 1, fail: 2 (variable)
n   | selenium:firefox | idb       | mapreduce | express-pouchdb-minimum | pass: 224, pend: 1, fail: 8
n   | selenium:firefox | idb       | mapreduce | CouchDB v3.1.1          | pass: 292, pend: 1, fail: 93 (variable)
n   | selenium:firefox | idb       | find      | pouchdb-express-router  | pass: 343, pend: 156, fail: 228
n   | selenium:firefox | idb       | find      | pouchdb-server          | pass: 642, pend: 268
n   | selenium:firefox | idb       | find      | express-pouchdb-minimum | pass: 325, pend: 134, fail: 7
n   | selenium:firefox | idb       | find      | CouchDB v3.1.1          | pass: 642, pend: 268
y*  | selenium:firefox | indexeddb | mapreduce | pouchdb-express-router  | pass: 376, fail: 19 (variable)
n   | selenium:firefox | indexeddb | mapreduce | pouchdb-server          | pass: 394, pend: 1, fail: 21 (variable)
n   | selenium:firefox | indexeddb | mapreduce | express-pouchdb-minimum | pass: 201, fail: 12
n   | selenium:firefox | indexeddb | mapreduce | CouchDB v3.1.1          | pass: 307, pend: 1, fail: 112 (variable)
n   | selenium:firefox | indexeddb | find      | pouchdb-express-router  | pass: 68, pend: 137, fail: 230
y*  | selenium:firefox | indexeddb | find      | pouchdb-server          | pass: 367, pend: 249, fail: 2
n   | selenium:firefox | indexeddb | find      | express-pouchdb-minimum | pass: 50, pend: 115, fail: 9
n   | selenium:firefox | indexeddb | find      | CouchDB v3.1.1          | pass: 367, pend: 249, fail: 2

One interesting thing that jumps out from this is that the `find` tests give the
same result for `pouchdb-server` and for CouchDB, with a couple of failures for
`indexeddb` but passing otherwise. The results aren't consistent across servers
and a lot of the tests are pending. I have not yet tried to run the
`integration` suite with different `SERVER` values so the results we have for
that suite are for `SERVER=pouchdb-express-router`.

The main thing we need to decide here is: which of the above tasks should be run
in CI, and why? What do we absolutely need to guarantee is working before
cutting a release of PouchDB? Once we know that we should enable these tasks in
CI and work to get them passing, prioritising the `idb` and `indexeddb`
adapters.

@garbados has started a [branch][gha-branch] to move the build to GitHub Actions
which looks very promising and should be more stable than Travis. Hopefully this
will let us enable some of the tasks that are currently commented out in the
Travis config.

I will also note down other questions that have occurred to me while working on
this:

- Why do we have multiple different ways of running PouchDB as a server
  (`pouchdb-express-router`, `pouchdb-server`, `express-pouch`)? Do we need all
  of them? Can some be removed in order to simplify the test setup? It would
  also be useful to know which test suites are actually expected to be affected
  by changing the `SERVER`, so that if we decide we need to run multiple
  `SERVER` values for compatibility testing in CI, we only re-run tests that
  would be affected by it.

- Why are dependencies pinned to exact versions, and could we loosen them up a
  bit? We spent a lot of time debugging why the integration tests were failing
  non-deterministically before finding that the bug had been fixed in
  `pouchdb-express-router` in 2019 and released as v0.0.11, but PouchDB was not
  running this because of its pinned dependencies.

- We currently run the Node tests for v8, v10 and v12. All the results I
  gathered above are using v12.22.5. The tests do not run correctly on v14 or
  v16, including browser-based tests. v12 is maintained until April 2022 so we
  may need to support newer versions before too long.

- Do we still use SauceLabs to run browser tests, or can we remove all the code
  for doing this?

- Any further opportunities for removing or simplifying things? Some of the
  issues we've encountered seem to stem from the complexity of the build setup
  code and we should look for ways we can remove anything we don't need.

[NH]: https://github.com/neighbourhoodie
[ci-branch]: https://github.com/neighbourhoodie/pouchdb/tree/fix/ci-improvements
[gha-branch]: https://github.com/neighbourhoodie/pouchdb/tree/feat/gha-garbados
[heartbeat-fix]: https://github.com/pouchdb/pouchdb-express-router/commit/30bd27a748ae69409864d6af87e84086f67eacde

**Comment by jcoglan** [comment]
To give an update on where we are with this work: we now have several PRs open that address some bugs and make improvements to the test suite itself. Those are #8350, #8351, #8358, #8359. Some of these are quite dependent on each other, for example:

- #8351 is needed to be able to test different adapters reliably and the other PRs rely on it if you want to test them
- #8359 changes every line of the `find` tests so will generate conflicts with other `find`-related changes

It would be great to get some of these merged before we open more, before we end up juggling a lot of dependent/conflicting pull requests :)

**Comment by jcoglan** [comment]
I'd also like to update `TESTING.md` to give clearer instructions about which tests to run, which combinations are supported, now that we understand it better, but I'd rather do that as a single task after we've made any changes we want.

**Comment by dheimoz** [comment]
@jcoglan Hey James. First of all thank you very much for the huge effort you and your team are doing. This is the best way to keep this project alive. 
I am finishing some projects, then I could allocate time for help you all.

Will try to assist at my best capacity.

I see there are conflicts at #8359, I wonder if could be addressed.

Once again, thanks for the commitment .

**Comment by jcoglan** [comment]
I've been meaning to round back to this issue for a while to give an update. As you know we're now running on GitHub Actions and we've figured out which combinations of settings and tasks we need to run to give reliable coverage and enable us to make releases. The tasks now configured in CI are:

- Run `integration`, `find` and `mapreduce` suites in the following ways:
  - against CouchDB 2.3 and 3.1
  - on all supported Node.js versions
  - in Firefox and Chrome
  - running the `leveldb` and `memory` adapters on Node.js`, and `idb`, `indexeddb` and `memory` in the browser (using `pouchdb-express-router` for the server)
  - against `pouchdb-server`, in Node.js and browsers
- Other tasks
  - `eslint`, which is run before all other tasks begin
  - test the Webpack build
  - run `npm test` with auto compaction
  - run `npm test` in performance mode
  - run `test-unit`, `test-fuzzy` and `test-component`
  - run `verfiy-build`

The coverage task is currently turned off. If we expand out the matrix of settings we now have configured, it looks like this:

```yml
strategy:
  matrix:
    include:
      - { couchdb: '2.3', node: '12', cmd: 'npm test' }
      - { couchdb: '2.3', node: '12', cmd: 'TYPE=find PLUGINS=pouchdb-find ADAPTERS=http npm test' }
      - { couchdb: '2.3', node: '12', cmd: 'TYPE=mapreduce ADAPTERS=http npm test' }
      - { couchdb: '3.1', node: '12', cmd: 'npm test' }
      - { couchdb: '3.1', node: '12', cmd: 'TYPE=find PLUGINS=pouchdb-find ADAPTERS=http npm test' }
      - { couchdb: '3.1', node: '12', cmd: 'TYPE=mapreduce ADAPTERS=http npm test' }
      - { couchdb: '2.3', client: 'selenium:firefox', cmd: 'npm test' }
      - { couchdb: '2.3', client: 'selenium:firefox', cmd: 'TYPE=find PLUGINS=pouchdb-find ADAPTERS=http npm test' }
      - { couchdb: '2.3', client: 'selenium:firefox', cmd: 'TYPE=mapreduce ADAPTERS=http npm test' }
      - { couchdb: '2.3', client: 'selenium:chrome', cmd: 'npm test' }
      - { couchdb: '2.3', client: 'selenium:chrome', cmd: 'TYPE=find PLUGINS=pouchdb-find ADAPTERS=http npm test' }
      - { couchdb: '2.3', client: 'selenium:chrome', cmd: 'TYPE=mapreduce ADAPTERS=http npm test' }
      - { couchdb: '3.1', client: 'selenium:firefox', cmd: 'npm test' }
      - { couchdb: '3.1', client: 'selenium:firefox', cmd: 'TYPE=find PLUGINS=pouchdb-find ADAPTERS=http npm test' }
      - { couchdb: '3.1', client: 'selenium:firefox', cmd: 'TYPE=mapreduce ADAPTERS=http npm test' }
      - { couchdb: '3.1', client: 'selenium:chrome', cmd: 'npm test' }
      - { couchdb: '3.1', client: 'selenium:chrome', cmd: 'TYPE=find PLUGINS=pouchdb-find ADAPTERS=http npm test' }
      - { couchdb: '3.1', client: 'selenium:chrome', cmd: 'TYPE=mapreduce ADAPTERS=http npm test' }
      - { node: '12', adapter: 'leveldb', cmd: 'npm test' }
      - { node: '12', adapter: 'leveldb', cmd: 'TYPE=find PLUGINS=pouchdb-find npm test' }
      - { node: '12', adapter: 'leveldb', cmd: 'TYPE=mapreduce npm test' }
      - { node: '12', adapter: 'memory', cmd: 'npm test' }
      - { node: '12', adapter: 'memory', cmd: 'TYPE=find PLUGINS=pouchdb-find npm test' }
      - { node: '12', adapter: 'memory', cmd: 'TYPE=mapreduce npm test' }
      - { client: 'selenium:firefox', adapter: 'idb', cmd: 'npm test' }
      - { client: 'selenium:firefox', adapter: 'idb', cmd: 'TYPE=find PLUGINS=pouchdb-find npm test' }
      - { client: 'selenium:firefox', adapter: 'idb', cmd: 'TYPE=mapreduce npm test' }
      - { client: 'selenium:firefox', adapter: 'indexeddb', cmd: 'npm test' }
      - { client: 'selenium:firefox', adapter: 'indexeddb', cmd: 'TYPE=find PLUGINS=pouchdb-find npm test' }
      - { client: 'selenium:firefox', adapter: 'indexeddb', cmd: 'TYPE=mapreduce npm test' }
      - { client: 'selenium:firefox', adapter: 'memory', cmd: 'npm test' }
      - { client: 'selenium:firefox', adapter: 'memory', cmd: 'TYPE=find PLUGINS=pouchdb-find npm test' }
      - { client: 'selenium:firefox', adapter: 'memory', cmd: 'TYPE=mapreduce npm test' }
      - { client: 'selenium:chrome', adapter: 'idb', cmd: 'npm test' }
      - { client: 'selenium:chrome', adapter: 'idb', cmd: 'TYPE=find PLUGINS=pouchdb-find npm test' }
      - { client: 'selenium:chrome', adapter: 'idb', cmd: 'TYPE=mapreduce npm test' }
      - { client: 'selenium:chrome', adapter: 'indexeddb', cmd: 'npm test' }
      - { client: 'selenium:chrome', adapter: 'indexeddb', cmd: 'TYPE=find PLUGINS=pouchdb-find npm test' }
      - { client: 'selenium:chrome', adapter: 'indexeddb', cmd: 'TYPE=mapreduce npm test' }
      - { client: 'selenium:chrome', adapter: 'memory', cmd: 'npm test' }
      - { client: 'selenium:chrome', adapter: 'memory', cmd: 'TYPE=find PLUGINS=pouchdb-find npm test' }
      - { client: 'selenium:chrome', adapter: 'memory', cmd: 'TYPE=mapreduce npm test' }
      - { client: 'node', cmd: 'npm test' }
      - { client: 'node', cmd: 'TYPE=find PLUGINS=pouchdb-find ADAPTERS=http npm test' }
      - { client: 'node', cmd: 'TYPE=mapreduce ADAPTERS=http npm test' }
      - { client: 'selenium:firefox', cmd: 'npm test' }
      - { client: 'selenium:firefox', cmd: 'TYPE=find PLUGINS=pouchdb-find ADAPTERS=http npm test' }
      - { client: 'selenium:firefox', cmd: 'TYPE=mapreduce ADAPTERS=http npm test' }
      - { client: 'selenium:chrome', cmd: 'npm test' }
      - { client: 'selenium:chrome', cmd: 'TYPE=find PLUGINS=pouchdb-find ADAPTERS=http npm test' }
      - { client: 'selenium:chrome', cmd: 'TYPE=mapreduce ADAPTERS=http npm test' }
      - { node: '12', cmd: 'CLIENT=selenium:firefox npm run test-webpack' }
      - { node: '12', cmd: 'AUTO_COMPACTION=true npm test' }
      - { node: '12', cmd: 'PERF=1 npm test' }
      - { node: '12', cmd: 'npm run test-unit' }
      - { node: '12', cmd: 'npm run test-component' }
      - { node: '12', cmd: 'npm run test-fuzzy' }
      - { node: '12', cmd: 'npm run verify-build' }
```

We have intentionally not covered every possible combination of settings but rather tried variations of each important thing: runtime platform, server backend, adapter, and so on. Importantly we are testing everything against CouchDB for a compatibility baseline, so if those tests pass we know all other passing tests are valid. We don't need to run all tests twice as we used to in the `find` and `mapreduce` suites. 

We've also tried to eliminate redundant tasks, for example by avoiding running every single test for all versions of CouchDB when many tests don't use CouchDB at all. This is somewhat tricky to achieve in GitHub Actions in a nice way because of restrictions on how YAML is used, but hopefully it saves time in CI by not running needless tasks.

Some remaining items we should investigate in future:

- We currently support Node.js v12, which will exit maintenance window in a few months. We should look at supporting v14, v16 and later.
- There is still a bunch of code in the build scripts that could be deleted or simplified, but it's not urgent.

We have got CI into much better shape than it was and hopefully clarified the docs for developers, especially in terms of communicating which combinations of settings are important. But if anyone finds something missing do fix it :)

Thanks to @AlbaHerrerias who's been instrumental in getting a lot of CI issues ironed out, and @janl and @garbados for the GHA migration work and various other fixes.
